# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateProduct.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class UpdateProductWindow(QWidget):
    def setupUi(self, Update ):
        Update .setObjectName("MainWindow")
        Update .resize(318, 501)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Update .setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Update )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.ImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ImageLabel.setText("")
        self.ImageLabel.setObjectName("ImageLabel")
        self.verticalLayout.addWidget(self.ImageLabel)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 150))
        self.frame_2.setMaximumSize(QtCore.QSize(300, 250))
        self.frame_2.setStyleSheet("background-color: rgb(255, 71,25);\n"
"font: 14pt \"Simplified Arabic Fixed\";")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.Name = QtWidgets.QLineEdit(self.frame_2)
        self.Name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Name.setObjectName("Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Name)
        self.Manufacturer = QtWidgets.QLineEdit(self.frame_2)
        self.Manufacturer.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Manufacturer.setObjectName("Manufacturer")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Manufacturer)
        self.Price = QtWidgets.QLineEdit(self.frame_2)
        self.Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Price.setObjectName("Price")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Price)
        self.Quota = QtWidgets.QLineEdit(self.frame_2)
        self.Quota.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Quota.setObjectName("Quota")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Quota)
        self.Availabillity = QtWidgets.QComboBox(self.frame_2)
        self.Availabillity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Availabillity.setObjectName("Availabillity")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Availabillity)
        self.Upload = QtWidgets.QPushButton(self.frame_2)
        self.Upload.setStyleSheet("background-color: rgb(255, 187, 14);\n"
"font: 14pt \"Simplified Arabic Fixed\";")
        self.Upload.setObjectName("Upload")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Upload)
        self.Submit = QtWidgets.QPushButton(self.frame_2)
        self.Submit.setStyleSheet("background-color: rgb(255, 187, 14);\n"
"font: 14pt \"Simplified Arabic Fixed\";")
        self.Submit.setObjectName("Submit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.Submit)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setStyleSheet("background-color: rgb(255, 187, 14);\n"
"font: 14pt \"Simplified Arabic Fixed\";")
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.verticalLayout.addWidget(self.frame_2)
        Update .setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Update )
        self.menubar.setGeometry(QtCore.QRect(0, 0, 318, 21))
        self.menubar.setObjectName("menubar")
        Update .setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Update )
        self.statusbar.setObjectName("statusbar")
        Update .setStatusBar(self.statusbar)

        self.retranslateUi(Update )
        QtCore.QMetaObject.connectSlotsByName(Update )

    def retranslateUi(self, Update ):
        _translate = QtCore.QCoreApplication.translate
        Update .setWindowTitle(_translate("MainWindow", "Product Information"))
        self.label.setText(_translate("MainWindow", "UPDATE PRODUCT"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Manufacturer"))
        self.label_5.setText(_translate("MainWindow", "Price"))
        self.label_6.setText(_translate("MainWindow", "Image"))
        self.label_7.setText(_translate("MainWindow", "Quota"))
        self.label_8.setText(_translate("MainWindow", "Availability"))
        self.Upload.setText(_translate("MainWindow", "Upload"))
        self.Submit.setText(_translate("MainWindow", "Submit"))
        self.pushButton.setText(_translate("MainWindow", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Update  = QtWidgets.QMainWindow()
    ui = UpdateProductWindow()
    ui.setupUi(Update )
    Update .show()
    sys.exit(app.exec_())
